language: ruby

rvm:
- 2.6.6

addons:
  postgresql: "9.6"

services:
  - postgresql

install:
  - bundle install
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn

before_script:
  - bundle exec rake db:create db:migrate RAILS_ENV=test

script:
  - bundle exec rspec
