name: Verify
on: [push, pull_request]

jobs:
  setup-environment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.16.2

  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Run RSpec Tests
        run: bundle exec rspec spec
